### ISSUE TITLE
关于使用Raycast提供的OpenInBrowse方法要先打开浏览器

### ISSUE THREAD

**Issue by LawrenceLiuQuanzhou** [Jax0rz/wechat#1]
作者可以直接把URL作为一个参数，然后执行 `curl URL` 就能不经过浏览器直接打开链接。

WeChatTweak 的作者其实也是用这种方式在Alfred中实现了跳转微信对应联系人。

即使不懂NodeJS，但我搜了下，在NodeJS里运行bash指令有很多方案，应该是可行的。

**Comment by Jax0rz** [comment]
已经实现，最近几天再增加一下判断微信是否安装还有其他一些小细节优化就会发布到Raycast Store了
